package org.jasm.test.tools;

public class GenerateInstructionsList {
	
	//private static String SOURCE = "AALOAD|AASTORE|ACONST_NULL|ARETURN|ARRAYLENGTH|ATHROW|BALOAD|BASTORE|CALOAD|CASTORE|D2F|D2I|D2L|DADD|DALOAD|DASTORE|DCMPG|DCMPL|DCONST_0|DCONST_1|DDIV|DMUL|DNEG|DREM|DRETURN|DSUB|DUP|DUP_X1|DUP_X2|DUP2|DUP2_X1|DUP2_X2|F2D|F2I|F2L|FADD|FALOAD|FASTORE|FCMPG|FCMPL|FCONST_0|FCONST_1|FCONST_2|FDIV|FMUL|FNEG|FREM|FRETURN|FSUB|I2B|I2C|I2D|I2F|I2L|I2S|IADD|IALOAD|IAND|IASTORE|ICONST_M1|ICONST_0|ICONST_1|ICONST_2|ICONST_3|ICONST_4|ICONST_5|IDIV|IMUL|INEG|IOR|IREM|IRETURN|ISHL|ISHR|ISUB|IUSHR|IXOR|L2D|L2F|L2I|LADD|LALOAD|LAND|LASTORE|LCMP|LCONST_0|LCONST_1|LDIV|LMUL|LNEG|LOR|LREM|LRETURN|LSHL|LSHR|LSUB|LUSHR|LXOR|MONITORENTER|MONITOREXIT|NOP|POP|POP2|RETURN|SALOAD|SASTORE|SWAP";
	//private static String SOURCE = "INVOKEINTERFACE|INVOKEDYNAMIC|ANEWARRAY|CHECKCAST|GETFIELD|GETSTATIC|INSTANCEOF|INVOKESPECIAL|INVOKESTATIC|INVOKEVIRTUAL|LDC2_W|LDC2|NEW|PUTFIELD|PUTSTATIC";
	//private static String SOURCE="ALOAD|ASTORE|DLOAD|DSTORE|FLOAD|FSTORE|ILOAD|ISTORE|LLOAD|LSTORE";
	private static String SOURCE = "GOTO|GOTO_W|IF_ACMPEQ|IF_ACMPNE|IF_ICMPEQ|IF_ICMPGE|IF_ICMPGT|IF_ICMPLE|IF_ICMPLT|IF_ICMPNE|IFEQ|IFGE|IFGT|IFLE|IFLT|IFNE|IFNONNULL|IFNULL|JSR|JSR_W";
	
	public static void main(String[] args) {
		String[] instrs = SOURCE.toLowerCase().split("\\|");
		StringBuffer buf = new StringBuffer();
		for (int i=0;i<instrs.length; i++) {
			if (i>0) {
				buf.append(", ");
			}
			String entry = instrs[i];
			entry = "["+entry+"](http://docs.oracle.com/javase/specs/jvms/se8/html/jvms-6.html#jvms-6.5."+entry+")";
			buf.append(entry);
		}
		
		System.out.println(buf.toString());
		
		
		

	}

}
